name: mirdnn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - biopython
  - scipy
  - scikit-learn
  - tqdm
  - viennarna
