name: mire2e
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch>=1.7
  - pytorch-cuda=11.8
  - pip
  - pip:
      - biopython>=1.78
      - scikit-learn>=0.23
      - tqdm
      - miRe2e
