name: dnnpremir
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - numpy
  - cudatoolkit=10.0
  - cudnn=7.6
  - viennarna
  - pip
  - pip:
      - tensorflow-gpu==1.14.0
      - keras==2.2.4
      - h5py==2.10.0
